# Массивы NumPY

### Создание массивов

In [7]:
import numpy as np

*__Создание одномерного массива__*

In [9]:
my_list = [1, 2, 3]

In [11]:
type(my_list)

list

In [13]:
# Приведем список к массиву
np.array(my_list)

array([1, 2, 3])

In [15]:
# Исходный список остался без изменений
type(my_list)

list

In [17]:
my_arr = np.array(my_list)

In [19]:
type(my_arr)

numpy.ndarray

*__Создание двумерного массива__*

In [23]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [25]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

*__Создание массивов с помощью встроенных функций__*

In [28]:
# Аналог обычной функции range (верхняя граница также не включается)
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [32]:
# Наример получим все чётные числа до 100
np.arange(0, 101, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

*__Создание массива из 0__*

In [35]:
# Нули с плавающей точкой
# Создание одномерного массива
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [37]:
# Создание двумерного массива - передаем кортеж из 2 чисел (сторки, колонки)
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

*__Создание массива из 1__*

In [44]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [46]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

*__Функция, которая возвращает набор равноотстоящих друг от друга числе в указанном диапазоне__*

In [55]:
# Передаем три параметра - начало диапазона, его конец и количество возвращаемых чисел
# ЛЕВЫЙ ДИАПАЗОН ВКЛЮЧАЕТСЯ В СОЗДАННЫЙ МАССИВ!
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [57]:
# Так как верхняя граница включается в диапазон - указываем 11
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [59]:
# Если запросим 10 чисел
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [61]:
np.linspace(0, 5, 21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

*__Создание единичной матрицы в которой на главной диаганали 1, а в других ячейках 0__*

In [64]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Создание случайных распределений чисел

*__Равномерное распределение__*

In [71]:
# 0 включается, а 1 - нет
# Создание одномерного массива
np.random.rand(1)

array([0.80192095])

In [73]:
# Создание двумерного массива (строки, колонки)
np.random.rand(5, 6)

array([[0.03961589, 0.60268336, 0.95109076, 0.39888262, 0.33402696,
        0.23087707],
       [0.81625299, 0.05454722, 0.30883368, 0.01239867, 0.67711268,
        0.1700528 ],
       [0.17405102, 0.99771781, 0.98940016, 0.6713918 , 0.47602094,
        0.32172326],
       [0.17017763, 0.25631587, 0.58296166, 0.6860036 , 0.25440703,
        0.76194201],
       [0.13006925, 0.34181025, 0.49852294, 0.71357001, 0.89508046,
        0.67897916]])

In [75]:
np.random.rand(5, 2)

array([[0.57064952, 0.42300396],
       [0.24694605, 0.696845  ],
       [0.55842696, 0.18512988],
       [0.64503737, 0.52425559],
       [0.86328772, 0.05888001]])

*__Нормальное распределение (распределение Гаусса)__*

In [81]:
# Стандартное нормальное распределение (мат.ож=0, дисп=1)
# Чем ближе к 0 - тем больше вер-ть получить число, чем дальше от 0 - тем меньше
np.random.randn(10)

array([-0.0183152 ,  1.28559891,  0.83783746,  0.79091134, -1.18370178,
       -0.81300861, -0.01619397,  0.33377701,  0.6436002 ,  1.48130603])

In [83]:
np.random.randn(2, 3)

array([[-0.09998916, -0.02032037, -0.21330898],
       [-0.36858362, -0.16707472, -1.01803121]])

In [85]:
# Целые случайные числа для равномерного случ. распред.
np.random.randint(0, 101, 5)

array([40, 68, 77, 18, 90])

In [87]:
np.random.randint(0, 101, (4, 5))

array([[47,  7, 80, 42, 26],
       [93, 81, 18, 82, 71],
       [99, 62, 57, 65, 10],
       [55, 36, 41, 39, 66]])

### Как сделать результаты воспроизводимыми

In [90]:
# Указываем в одной ячейке
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

### Полезное

In [93]:
arr = np.arange(0, 25)

In [95]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

*__Изменение формы массива__*

In [101]:
# Надо указывать размер так, чтобы все поместилось
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [103]:
ran_array = np.random.randint(0, 101, 10)

In [105]:
ran_array

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

*__Нахождение max__*

In [107]:
ran_array.max()

99

*__Нахождение min__*

In [111]:
ran_array.min()

2

*__Индекс max числа__*

In [114]:
# Нумерация индексов - с 0
ran_array.argmax()

5

*__Индекс min числа__*

In [117]:
# Нумерация индексов - с 0
ran_array.argmin()

7

*__Тип данных массива__*

In [122]:
# Так как не метод, а атрибут - то без ()
ran_array.dtype

dtype('int32')

*__Размер(форма) массива__*

In [125]:
# Так как не метод, а атрибут - то без ()
# (25,) - так как м.б. 3 случая: одномерный массив из 25 эл-ов, двумерный массив (1 строка, 25 колонок)
# двумерный массив (25 сторк, 1 колонка)
arr.shape

(25,)

In [127]:
arr_1 = arr.reshape(5, 5)

In [129]:
arr_1.shape

(5, 5)