# Опреации NumPy

In [9]:
import numpy as np

In [11]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Арифметика

In [13]:
# Применится ко всем элементам.
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
# Применится ко всем элементам.
arr-2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [17]:
# Массивы должны быть одинаковы.
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [21]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
# Работа numpy с делением на 0.
arr / arr

C:\Users\chern\AppData\Local\Temp\ipykernel_14224\3322110557.py:2: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [25]:
1 / arr

C:\Users\chern\AppData\Local\Temp\ipykernel_14224\1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

### Универсальный функции для массивов

In [28]:
# Квадратный корень.
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [30]:
# Синус.
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [32]:
# Логарифм.
np.log(arr)

C:\Users\chern\AppData\Local\Temp\ipykernel_14224\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

### Результаты функций агрегации массивов

In [35]:
# Сумма всех чисел.
arr.sum()

45

In [37]:
# Среднее значение.
arr.mean()

4.5

In [39]:
# Максимум в массиве.
arr.max()

9

In [41]:
# Дисперсия.
arr.var()

8.25

In [43]:
# Среднеквадратичное отклонение.
arr.std()

2.8722813232690143

*__Для двумерного массива__*

### Использование горизонтальной и вертикальной осей.

In [53]:
arr_2d = np.arange(0, 25).reshape(5, 5)
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
arr_2d.shape

(5, 5)

In [57]:
# Сумма всех эл-ов матрицы и по строкам и по колонкам.
arr_2d.sum()

300

In [59]:
# Сумма по колонкам ([0+5+10+15+20], [1+6+11+16+21] и т.д.).
arr_2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [61]:
# Сумма по сторкам
arr_2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])