# Индексация массивов в NumPy

In [2]:
import numpy as np

In [4]:
arr = np.arange(0, 11)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

*__Выбор одного числа__*

In [9]:
# Индексация начинается с 0
arr[8]

8

*__Выбор диапазона__*

In [12]:
# Начальная и конечная позиция (конечная не включается)
arr[1:5]

array([1, 2, 3, 4])

In [14]:
arr[:5]

array([0, 1, 2, 3, 4])

In [16]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [18]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Опреации broadcast
В массиве numpy можно взять новое значение и записать его сразу во множество ячеек массива, в отличие от обычных
списков в python.

In [22]:
# Для обычных списокв в python такое невозможно
arr[0:5] = 100

In [24]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [26]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

*__Slice для массива__*

In [28]:
slice_of_array = arr[0:5]
slice_of_array

array([0, 1, 2, 3, 4])

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
slice_of_array[:] = 99
slice_of_array

array([99, 99, 99, 99, 99])

In [36]:
# Когда создали slice_of_array - создали не отдельные копии эл-ов, а ссылки
# на эл-ты исходного массива.
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [40]:
# Для создания полноценной копии неопходимо сделать так:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [44]:
# Теперь изменения будут только в копии исходного массива.
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [46]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

### Для двумерных массивов

In [49]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

*__Индексирование__*

In [55]:
arr_2d.shape

(3, 3)

In [57]:
# Получение первой строки.
arr_2d[0]

array([ 5, 10, 15])

In [59]:
# Получение последней строки (можно 0, можно -1).
arr_2d[-1]

array([35, 40, 45])

In [61]:
# Один элемент из массива - первый способ.
arr_2d[1][1]

25

In [63]:
# Второй способ получения одного элемента.
arr_2d[1, 1]

25

In [65]:
arr_2d[0, 2]

15

*__Срезы__*

In [69]:
# Сначала строки(0 и 1 без 2).
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [71]:
# Столбцы, начния с первого.
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

### Выбор по условию

In [92]:
arr_1 = np.arange(1, 11)
arr_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
arr_1 > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [96]:
bool_arr = arr_1 > 4

In [98]:
# Выбор эл-ов больше 4 в исходном массиве.
arr_1[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [102]:
# Можно выполнить так:
arr_1[arr_1>4]

array([ 5,  6,  7,  8,  9, 10])